### PR TITLE
Update of some dependencies

### PR DESCRIPTION
**Pull request by pedrofurtado**

### CODE REVIEW

**Comment by dwieeb** [comment]
@pedrofurtado The tests are failing. It looks like we need to do some more work before v3 can be upgraded to Angular 6.

**Comment by pedrofurtado** [comment]
@dwieeb What is the repository where `ionic-angular` is versioned? I will make the changes there too.

**Comment by dwieeb** [comment]
@pedrofurtado You will want to look at the `v3` branch of the Ionic repo: https://github.com/ionic-team/ionic/tree/v3

**Comment by pedrofurtado** [comment]
@dwieeb Another doubt: To change `ionic-native` v3 I have to navigate in what repository (or branch)?

**Comment by dwieeb** [comment]
@pedrofurtado You'll want to use `master` for 4.x of `ionic-native` (that's what's in `package.json`).

**Comment by pedrofurtado** [comment]
> @pedrofurtado You'll want to use `master` for 4.x of `ionic-native` (that's what's in `package.json`).

yeah, I make confusion here (the ionic-angular that is in version 3x, not ionic-native 😃 )

**Comment by pedrofurtado** [comment]
@dwieeb I've created two another PR's in related repos:

https://github.com/ionic-team/ionic-native/pull/2790
https://github.com/ionic-team/ionic/pull/16051

Let me know if looks good for merge (the tests passing). The `rxjs-compat` is required until all repos release a version of rxjs in 6.x. Then, it will be possible to remove this library.

**Comment by dwieeb** [comment]
@pedrofurtado I'm so sorry... I was being stupid yesterday. There's already a `v5` branch for Ionic Native with the rxjs updates: https://github.com/ionic-team/ionic-native/tree/v5

Can we update this PR to use the beta version of v5? That will be easiest. Sorry again, I must have not been thinking.

**Comment by pedrofurtado** [comment]
@dwieeb No problems! :+1: 

But, anyway, is it great to provide the rxjs 6 for all users that already have `v4` of `ionic-native`? The use of `rxjs-compat`, for a while, could help updates for devs until they upgrade to `ionic-native@5.x` later. Because of `rxjs-compat`, the users from v4 will not be affected.

**Comment by dwieeb** [comment]
@pedrofurtado For existing users, I'm hesitant to include the upgrade in a minor version release. It would require the `rxjs-compat` package installation on their part. Also there are breaking changes not covered: https://github.com/ReactiveX/rxjs/blob/master/docs_app/content/guide/v6/migration.md#breaking-changes-not-covered-by-rxjs-compat

**Comment by pedrofurtado** [comment]
@pedrofurtado Hmm, you are right. Maybe it's better to not include minor version with possible breaking changes.

**Comment by dwieeb** [comment]
@pedrofurtado I'm sorry, I didn't mean for you to close this! I just meant we can use Ionic Native v5 for Ionic v3. That would be simpler!

**Comment by pedrofurtado** [comment]
@dwieeb I prefer to create another PR with only the upgrade of ionic-native. Another dependencies updates from v3 would be nice, and I can provide some PR's later for each isolated update 👍 
Thus, the upgrade process from v3 to future stable v4 can be more easy 🤝

**Pull request closed without merging**
