### PR TITLE
fix(react-vite,vue-vite): add vitest type reference

### PR DESCRIPTION
**Pull request by diegoazh**
This change solves the TS error on the Vite config object following the Vitest documentation.

### CODE REVIEW

**Comment by sean-perkins** [comment]
Hello @diegoazh thanks for the contribution! Can you provide a link to the documentation that suggests this approach?

**Comment by diegoazh** [comment]
Sure @sean-perkins, you can check it [here](https://vitest.dev/guide/#configuring-vitest), on the second code example.

**Comment by diegoazh** [comment]
do you need anything else @sean-perkins?

**Comment by diegoazh** [comment]
What happens with this PR? How should I continue to merge this change?

**Comment by diegoazh** [comment]
💪🏼 all tests passed successfully 🎉, let me know if I can help with anything else to merge this. Thank you.

**Review by sean-perkins — APPROVED** [review]
Great work 👍

**Pull request merged**
