### PR TITLE
Remove .gitignore, add support for JHipster Ionic entity generator

### PR DESCRIPTION
**Pull request by mraible**

### CODE REVIEW

**Comment by dwieeb** [comment]
@mraible Looks good. Everything is working 👍 I used `ionic start jhip oktadeveloper/jhipster`

The `welcome.message.js` file was included, but not needed (the CLI uses the `starter.config.json` file for the welcome message).

**Comment by mraible** [comment]
If I don't keep this file in my repo, where do you suggest I keep it? I like to have the raw source saved so I can change and regenerate.

**Comment by dwieeb** [comment]
Yeah, good point. Maybe we can have a `.utils/` folder that gets ignored by the build process. Thoughts?

**Comment by mraible** [comment]
That could work, but a better solution would be to use conventions IMHO.

Proposal: If you have a `welcome.message.js` in the root directory, the build process will automatically update `starter.config.json` when you build. 

FWIW, in order to convert the one in my starter to copy/paste into `starter.config.json`, I copy it to `ionic-angular/official/note.js` and run `node note.js`. If I run it from my starter's root directory, I get the following error:

```
[mraible:~/dev/ionic-jhipster-starter] master* ± node welcome.message.js
module.js:538
    throw err;
    ^

Error: Cannot find module 'chalk'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/mraible/dev/ionic-jhipster-starter/welcome.message.js:1:77)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```

**Pull request merged**
