### PR TITLE
Add Ionic starter for JHipster

### PR DESCRIPTION
**Pull request by mraible**
I'm not sure this has to be in this repository, but it seems to be the only way to run `ionic start myApp oktadeveloper/jhipster`. If there's another way to run that command and pull from https://github.com/oktadeveloper/ionic-jhipster-starter, I'd love to hear about it!

### CODE REVIEW

**Comment by dwieeb** [comment]
Hi @mraible! Starter is looking great.

Couple things:
1. I tried doing an `npm install` of your generated starter and got the issue, which I resolved by updating [this dep](https://github.com/oktadeveloper/ionic-jhipster-starter/blob/master/ionic.starter.json#L14) to use latest.

    ```
    npm ERR! code ETARGET
    npm ERR! notarget No matching version found for generator-jhipster-ionic@^0.0.1
    npm ERR! notarget In most cases you or one of your dependencies are requesting
    npm ERR! notarget a package version that doesn't exist.
    ```

1. I noticed your starter is using Angular 4. Is there anything stopping you from supporting Angular 5 and Ionic Angular 3.9.2? If not, update your `baseref` to use this commit or later: https://github.com/ionic-team/starters/commit/b77cf2c89491beffd1939d3554a5520c89caebad

Let me know if you have any questions. 😄

**Comment by dwieeb** [comment]
Update: This commit now brings in latest deps: https://github.com/ionic-team/starters/commit/5964277615322dd74d8d84528ce5d01b07acbed8

So a `baseref` of `5964277615322dd74d8d84528ce5d01b07acbed8` would be best, if using Angular 5.

**Comment by mraible** [comment]
@dwieeb OK, I've removed the missing dependency and updated to the suggested `basehref`.

One question I have is about the workflow for updating this starter. Once it's merged, so I still need to perform the following steps?

1. Push to https://github.com/oktadeveloper/ionic-jhipster-starter to change files.
2. Run `git pull` in my local `starters/ionic-angular/community/oktadeveloper/jhipster` directory.
3. Run `git add . && git commit -m "Update files"` and create another PR.

Step 3 seems like it might not be necessary, but I'm not sure. Thanks!

**Comment by dwieeb** [comment]
@mraible Yes, those would be the steps. I've added them to the contributing docs: https://github.com/ionic-team/starters/blob/master/CONTRIBUTING.md#community-starters

Okay, looking good. One other thing I noticed is that the following files do not have significant changes from the base files and can be removed from your starter repo (they'll be brought in from the base files):
- `src/theme/variables.scss`
- `src/index.html`
- `src/manifest.json`
- `src/service-worker.js`

**Comment by mraible** [comment]
@dwieeb Is there anything else I need to do to get this merged/deployed? I'd like to show this at a conference tomorrow (Wednesday). I'm currently in Casablanca, Morocco, so GMT time zone.

**Comment by dwieeb** [comment]
@mraible All merged, but I didn't catch your addition of the `.gitignore` file, which overwrites the base `.gitignore`. You can use the `.git/info/exclude` file.  I added this to the docs: https://github.com/ionic-team/starters/blob/master/CONTRIBUTING.md#community-starters

**Pull request merged**
