### PR TITLE
Add jhipster starter for Ionic4

### PR DESCRIPTION
**Pull request by fleboulch**

### CODE REVIEW

**Comment by fleboulch** [comment]
@mraible 
CI is failing and I saw in history you spent some times to get tests passing.
Do you have an idea about this issue or do you know someone else to help me to fix CI?

Some pointers about my search
- https://github.com/GregOnNet/ionic-4-jest-setup
- https://medium.com/@gregor.woiwode/how-to-setup-jest-in-an-ionic-4-project-ff1e5b72dd79
- https://github.com/ionic-team/ionic/issues/15695
- https://github.com/facebook/jest/issues/2081

**Comment by mraible** [comment]
@fleboulch Do the Jest tests pass when you run them locally? If so, maybe @dwieeb can help.

Also, this branch is out-of-date, so you might want to update it.

**Comment by fleboulch** [comment]
@mraible no they don't pass on local.
Yes I will rebase it

**Comment by mraible** [comment]
@fleboulch I created a new PR that (hopefully) fixes the tests: https://github.com/ionic-team/starters/pull/759

**Comment by fleboulch** [comment]
awesome @mraible 
thanks a lot ! I think we should update the generator to offer only ionic3 starter as v4 starter doesn't provide entity support yet.
I started working on it but it's not ready for production

**Comment by vivekmore** [comment]
@mraible @fleboulch 
I believe I got the unit tests passing locally.
   https://github.com/oktadeveloper/generator-jhipster-ionic/pull/70

**Comment by mhartington** [comment]
closing as of https://github.com/ionic-team/starters/pull/759

**Pull request closed without merging**
