### PR TITLE
feature(): ionic-super-starter project

### PR DESCRIPTION
**Pull request by danielsogl**
Repo:  https://github.com/danielsogl/ionic-super-starter

### CODE REVIEW

**Comment by dwieeb** [comment]
You shouldn't overwrite `package.json`. Please use the `packageJson` key in your manifest so keys are merged in with the base. Here's what it would look like for your project:

```json
{
  "name": "Ionic Super Starter",
  "baseref": "9ae58ee0e10a42c6b8b0729bff818dac9c249d7b",
  "packageJson": {
    "scripts": {
      "docs": "./node_modules/.bin/compodoc -d ./public/docs/ -p ./tsconfig.json -n \"Ionic Super - Documentation\"",
      "test": "jest",
      "test:watch": "jest --watch",
      "test:ci": "jest --runInBand",
      "test:coverage": "jest --coverage",
      "e2e": "npm run e2e-update && npm run e2e-test",
      "e2e-test": "protractor ./test-config/protractor.conf.js",
      "e2e-update": "webdriver-manager update --standalone false --gecko false"
    },
    "devDependencies": {
      "@angular/cli": "1.4.8",
      "@compodoc/compodoc": "^1.0.1",
      "@types/jasmine": "^2.5.41",
      "@types/jest": "^21.1.4",
      "@types/node": "^8.0.45",
      "angular2-template-loader": "^0.6.2",
      "html-loader": "^0.5.1",
      "ionic-mocks-jest": "^1.0.3",
      "istanbul-instrumenter-loader": "^3.0.0",
      "jasmine": "^2.5.3",
      "jasmine-spec-reporter": "^4.1.0",
      "jest": "^21.2.1",
      "jest-preset-angular": "^4.0.1",
      "null-loader": "^0.1.1",
      "protractor": "^5.1.1",
      "ts-loader": "^3.0.3",
      "ts-node": "^3.0.2"
    },
    "jest": {
      "preset": "jest-preset-angular",
      "setupTestFrameworkScriptFile": "<rootDir>/src/setupJest.ts",
      "transformIgnorePatterns": [
        "node_modules/(?!@ngrx|@ionic-native|@ionic)"
      ],
      "coveragePathIgnorePatterns": [
        "<rootDir>/e2e/"
      ],
      "collectCoverageFrom": [
        "**/*.{ts}",
        "!**/*d.{ts}",
        "!**/*interface.{ts}",
        "!**/*module.{ts}",
        "!**/*main.{ts}",
        "!**/node_modules/**"
      ],
      "moduleFileExtensions": [
        "ts",
        "js",
        "json"
      ],
      "coverageReporters": [
        "json",
        "lcov",
        "text"
      ],
      "coverageDirectory": "./public/coverage"
    }
  }
}
```

Also, please don't include `package-lock.json`.

Any way we can have you not overwrite the [base `tsconfig.json`](https://github.com/ionic-team/starters/blob/master/ionic-angular/base/tsconfig.json) with [yours](https://github.com/danielsogl/ionic-super-starter/blob/master/tsconfig.json)? Looks like the only change is adding ` "**/*.spec.ts"` to the `exclude` key. That's something we can just add to the base, I wouldn't mind.

Same with `.editorconfig`, `.gitignore`, `tslint.json`.

Please remove `config.xml` and `resources/`, they will be added incrementally as part of enabling the Cordova "integration" in the Ionic CLI.

**Comment by dwieeb** [comment]
@danielsogl The repo looks good now, you just have to update the submodule in this PR to use the latest git sha.

**Comment by danielsogl** [comment]
Done

**Comment by dwieeb** [comment]
@danielsogl I noticed the path of your starter is `ionic-angular/community/danielsogl/ionic-super-starter`, which means the command for your starter will be:

```
ionic start myApp danielsogl/ionic-super-starter
```

Is that desirable? or would you prefer `danielsogl/super`, in which case the path would need to be `ionic-angular/community/danielsogl/super`.

**Comment by dwieeb** [comment]
@danielsogl I'm getting a bunch of typescript errors after trying `ionic serve`: 

```
[20:02:11]  typescript: node_modules/@types/jasmine/index.d.ts, line: 15
            Duplicate identifier 'describe'.

        5:   * A focused it
      L16:   * If suites or specs are focused, only those that are focused will be executed.

[20:02:11]  typescript: node_modules/@types/jasmine/index.d.ts, line: 16
            Duplicate identifier 'fdescribe'.

      L15:  * A focused it
      L16:  * If suites or specs are focused, only those that are focused will be executed.
      L17:  * @param expectation

[20:02:11]  typescript: node_modules/@types/jasmine/index.d.ts, line: 17
            Duplicate identifier 'xdescribe'.

      L16:  * If suites or specs are focused, only those that are focused will be executed.
      L17:  * @param expectation
      L18:  * @param assertion

[20:02:11]  typescript: node_modules/@types/jasmine/index.d.ts, line: 26
            Duplicate identifier 'it'.

      L25:  * Mark a spec as pending, expectation results will be ignored.
      L26:  * If you call the function pending anywhere in the spec body, no matter the expectations, the spec will be m
      L27:  * @param reason

[20:02:11]  typescript: node_modules/@types/jasmine/index.d.ts, line: 35
            Duplicate identifier 'fit'.

      L34:  * @param action Function that contains the code to setup your specs.
      L35:  * @param timeout Custom timeout for an async beforeEach.

[20:02:11]  typescript: node_modules/@types/jasmine/index.d.ts, line: 36
            Duplicate identifier 'xit'.

      L35:   * @param timeout Custom timeout for an async beforeEach.
      L37:  declare function beforeEach(action: (done: DoneFn) => void, timeout?: number): void;

[20:02:11]  typescript: node_modules/@types/jasmine/index.d.ts, line: 51
            Duplicate identifier 'beforeEach'.

      L50:   * @param timeout Custom timeout for an async beforeAll.
      L52:  declare function beforeAll(action: (done: DoneFn) => void, timeout?: number): void;

[20:02:11]  typescript: node_modules/@types/jasmine/index.d.ts, line: 58
            Duplicate identifier 'afterEach'.

      L57:  * @param action Function that contains the code to teardown your specs.
      L58:  * @param timeout Custom timeout for an async afterAll

[20:02:11]  typescript: node_modules/@types/jasmine/index.d.ts, line: 66
            Duplicate identifier 'beforeAll'.

      L66:  declare function expect(spy: Function): jasmine.Matchers<any>;

[20:02:11]  typescript: node_modules/@types/jasmine/index.d.ts, line: 74
            Duplicate identifier 'afterAll'.

      L75:   * Create an expectation for a spec.

[20:02:11]  typescript: node_modules/@types/jasmine/index.d.ts, line: 80
            Cannot redeclare block-scoped variable 'expect'.

      L81:   * Explicitly mark a spec as failed.

[20:02:11]  typescript: node_modules/@types/jasmine/index.d.ts, line: 86
            Cannot redeclare block-scoped variable 'expect'.

      L86:  /** Action method that should be called when the async work is complete */
      L87:  interface DoneFn extends Function {

[20:02:11]  typescript: node_modules/@types/jasmine/index.d.ts, line: 92
            Cannot redeclare block-scoped variable 'expect'.

      L91:      fail: (message?: Error | string) => void;

[20:02:11]  typescript: node_modules/@types/jasmine/index.d.ts, line: 130
            Duplicate identifier 'clock'.

     L129:      function createSpyObj<T>(baseName: string, methodNames: any[] | {[methodName: string]: any}): SpyObj<T>;
     L131:      function createSpyObj(baseName: string, methodNames: any): any;

[20:02:11]  typescript: node_modules/@types/jasmine/index.d.ts, line: 183
            All declarations of 'ObjectContaining' must have identical type parameters.

     L183:      interface WaitsBlock extends Block {
     L184:          new (env: Env, timeout: number, spec: Spec): any;

[20:02:11]  typescript: node_modules/@types/jasmine/index.d.ts, line: 214
            Duplicate identifier 'CustomEqualityTester'.

     L213:  interface CustomMatcherResult {
      214:      pass: boolean;
     L215:      message?: string;

[20:02:11]  typescript: node_modules/@types/jasmine/index.d.ts, line: 221
            Duplicate identifier 'CustomMatcherFactory'.

     L220:      contains<T>(haystack: ArrayLike<T> | string, needle: any, customTesters?: CustomEqualityTester[]): boolean;
     L221:      buildFailureMessage(matcherName: string, isNot: boolean, actual: any, ...expected: any[]): string;

[20:02:11]  typescript: node_modules/@types/jasmine/index.d.ts, line: 229
            All declarations of 'message' must have identical modifiers.

     L228:          clearInterval: void;
     L229:          updateInterval: number;

[20:02:11]  typescript: node_modules/@types/jasmine/index.d.ts, line: 698
            Cannot redeclare block-scoped variable 'DEFAULT_TIMEOUT_INTERVAL'.

     L697:  execute(files: any, filterString: any): any;
     L698:  exitCodeCompletion(passed: any): void;
     L699:  loadConfig(config: any): void;

[20:02:11]  typescript: node_modules/@types/jest/index.d.ts, line: 14
            Duplicate identifier 'beforeAll'.

      L14:  declare const expect: jest.Expect;

[20:02:11]  typescript: node_modules/@types/jest/index.d.ts, line: 15
            Duplicate identifier 'beforeEach'.

      L14:  declare const expect: jest.Expect;
      L16:  interface NodeRequire {

[20:02:11]  typescript: node_modules/@types/jest/index.d.ts, line: 16
            Duplicate identifier 'afterAll'.

      L16:  interface NodeRequire {

[20:02:11]  typescript: node_modules/@types/jest/index.d.ts, line: 17
            Duplicate identifier 'afterEach'.

      L16:  interface NodeRequire {
      L18:       * Returns the actual module instead of a mock, bypassing all checks on

[20:02:11]  typescript: node_modules/@types/jest/index.d.ts, line: 18
            Duplicate identifier 'describe'.

      L18:   * Returns the actual module instead of a mock, bypassing all checks on
      L19:   * whether the module should receive a mock implementation or not.

[20:02:11]  typescript: node_modules/@types/jest/index.d.ts, line: 19
            Duplicate identifier 'fdescribe'.

      L18:  * Returns the actual module instead of a mock, bypassing all checks on
      L19:  * whether the module should receive a mock implementation or not.

[20:02:11]  typescript: node_modules/@types/jest/index.d.ts, line: 20
            Duplicate identifier 'xdescribe'.

      L19:   * whether the module should receive a mock implementation or not.
      L21:  requireActual(moduleName: string): any;

[20:02:11]  typescript: node_modules/@types/jest/index.d.ts, line: 21
            Duplicate identifier 'it'.

      L21:  requireActual(moduleName: string): any;

[20:02:11]  typescript: node_modules/@types/jest/index.d.ts, line: 22
            Duplicate identifier 'fit'.

      L21:  requireActual(moduleName: string): any;
      L23:   * Returns a mock module instead of the actual module, bypassing all checks

[20:02:11]  typescript: node_modules/@types/jest/index.d.ts, line: 23
            Duplicate identifier 'xit'.

      L23:   * Returns a mock module instead of the actual module, bypassing all checks
      L24:   * on whether the module should be required normally or not.

[20:02:11]  typescript: node_modules/@types/jest/index.d.ts, line: 27
            Cannot redeclare block-scoped variable 'expect'.

      L26:      requireMock(moduleName: string): any;

[20:02:11]  typescript: node_modules/@types/jest/index.d.ts, line: 551
            Cannot redeclare block-scoped variable 'DEFAULT_TIMEOUT_INTERVAL'.

     L550:      function stringMatching(value: string | RegExp): Any;
     L552:      interface Clock {

[20:02:11]  typescript: node_modules/@types/jest/index.d.ts, line: 552
            Duplicate identifier 'clock'.

     L552:      interface Clock {
     L553:          install(): void;

[20:02:11]  typescript: node_modules/@types/jest/index.d.ts, line: 556
            Generic type 'ObjectContaining<T>' requires 1 type argument(s).

     L556:   * Calls to any registered callback are triggered when the clock isticked forward
     L557:   * via the jasmine.clock().tick function, which takes a number of milliseconds.

[20:02:11]  typescript: node_modules/@types/jest/index.d.ts, line: 588
            All declarations of 'ObjectContaining' must have identical type parameters.

     L587:      argsForCall: any[];
     L588:      wasCalled: boolean;

[20:02:11]  typescript: node_modules/@types/jest/index.d.ts, line: 696
            Duplicate string index signature.

                interface CustomMatcher {
     L697:          compare<T>(actual: T, expected: T): CustomMatcherResult;

[20:02:11]  typescript: node_modules/@types/jest/index.d.ts, line: 699
            Duplicate identifier 'CustomMatcherFactory'.

     L698:          compare(actual: any, expected: any): CustomMatcherResult;

[20:02:11]  typescript: node_modules/@types/jest/index.d.ts, line: 707
            Duplicate identifier 'CustomEqualityTester'.

     L706:  interface ArrayLike<T> {
     L707:      length: number;
     L708:      [n: number]: T;

[20:02:11]  typescript: node_modules/@types/jest/index.d.ts, line: 716
            Subsequent variable declarations must have the same type. Variable 'message' must be of type 'string', but
            here has type 'string | (() => string)'.

     L715:      // https://facebook.github.io/jest/docs/en/configuration.html#transform-object-string-string
     L716:      // const transformer: Transformer;

[20:02:11]  typescript: node_modules/@types/jest/index.d.ts, line: 716
            All declarations of 'message' must have identical modifiers.

     L715:      // https://facebook.github.io/jest/docs/en/configuration.html#transform-object-string-string
     L716:      // const transformer: Transformer;

[20:02:11]  typescript: node_modules/@types/jest/index.d.ts, line: 721
            Duplicate number index signature.

     L721:      // https://facebook.github.io/jest/docs/en/configuration.html#testrunner-string
     L722:      // const testRunner: TestFramework;
```

**Comment by danielsogl** [comment]
Because of the missing exclude *spec.ts configuration in the base tsconfig file.

**Comment by dwieeb** [comment]
@danielsogl I added the key locally but still getting the errors. They're happening in `node_modules` for some  reason: `node_modules/@types/jest/index.d.ts` and `node_modules/@types/jasmine/index.d.ts`.

Can you also answer this? https://github.com/ionic-team/starters/pull/1#issuecomment-342026113

**Comment by danielsogl** [comment]
The tsconfig file should look like this.

```
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["dom", "es2015"],
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "target": "es5",
    "typeRoots": ["../node_modules/@types"]
  },
  "include": ["src/**/*.ts"],
  "exclude": ["node_modules", "**/*spec.ts"],
  "compileOnSave": false,
  "atom": {
    "rewriteTsconfig": false
  }
}
```

Add "**/*spec.ts" to the exludes and also add the "typeRoots": ["../node_modules/@types"] config.

To answer your first question you are right. I should rename the repo. But I think ionic-super would be a good name.

**Comment by dwieeb** [comment]
@danielsogl Thanks, I got it working. Missing `"typeRoots": ["../node_modules/@types"]` was the culprit. I thought `node_modules/@types` was added to "type roots" by typescript automatically? app-scripts must be using `src/` as cwd.

**Comment by dwieeb** [comment]
@danielsogl So only things left would be to

1) Change the path of the submodule to `danielsogl/super` (if that's the name you want)

2) Change the installation instructions here: https://github.com/danielsogl/ionic-super-starter#installation

```
ionic start ionic-super-starter danielsogl/super
```

**Comment by danielsogl** [comment]
done!

**Comment by dwieeb** [comment]
@danielsogl One more thing... you need to update your `baseref` to `9b3d060bca61d513450c330de84cb9b468cf7387`, because that's where I configured the base `tsconfig.json`: https://github.com/ionic-team/starters/commit/9b3d060bca61d513450c330de84cb9b468cf7387

**Comment by danielsogl** [comment]
Finally ^^

**Comment by dwieeb** [comment]
🎉 All merged in. It works great!!

You can test this with the alpha CLI. `npm i -g ionic@canary`.

Messaged you on slack btw.

**Pull request closed without merging**
