### PR TITLE
Remove ng-jhipster; add npm 7 compatibility

### PR DESCRIPTION
**Pull request by mraible**

### CODE REVIEW

**Comment by mraible** [comment]
@mhartington Can I get a merge, please?

**Comment by mraible** [comment]
FWIW, I tried changing the Ionic for JHipster module to pull directly from the `oktadeveloper/ionic-jhipster-starter` [repo](https://github.com/oktadeveloper/ionic-jhipster-starter) when running `ionic start`. However, it doesn't seem to work as well as pulling from 'oktadeveloper/jhipster'.

**Comment by mraible** [comment]
Closing and re-opening to see if I can get the build unstuck.

**Comment by mhartington** [comment]
Not sure what the CI issue was, but merged in! Thanks for this!

**Pull request merged**
