### PR TITLE
refactor(angular): switch to @ionic/angular-toolkit

### PR DESCRIPTION
**Pull request by dwieeb**

### CODE REVIEW

**Comment by 25121294** [comment]
Hey there, I don't know what's up but after your commit I can't start the aws starter.

**Comment by dwieeb** [comment]
@25121294 This commit shouldn't change the aws starter. Create a new issue so I can take a look.

**Comment by rapropos** [comment]
This causes peer dependency mismatches for me on a new blank project. `@ionic/angular-toolkit@1.0.0` wants 0.9.0-beta.3 of @angular-devkit/* but `~0.7.2` is declared in `package.json`. Might it be prudent to wait on this switchover until you are going to move entirely to @angular/cli 7?

**Comment by dwieeb** [comment]
@rapropos Yeah... I was noticing that as well. I think the peer deps [here](https://github.com/ionic-team/angular-toolkit/blob/master/package.json#L59-L62) are just too strict. They work with `~0.7.2`.

**Comment by squistbe** [comment]
I have tried `npm install --save-dev @ionic/angular-toolkit` and I am getting an error `Not Found: @ionic/angular-toolkit@latest`.

**Pull request merged**
